using System.Collections;
using System.Collections.Generic;
using UnityEngine;

 public class EnemyMovement : MonoBehaviour
{  
        [SerializeField] float moveSpeed = 3f;
        Rigidbody2D rb;

        void Start()
        {
            rb = GetComponent<Rigidbody2D>();
        }

        void Update()
        {
            rb.velocity = new Vector2(moveSpeed, 0f);
        }
    void OnCollisionEnter2D(Collision2D collision)
    {
        moveSpeed = -moveSpeed;
        FlipSprite();
    }

    void OnTriggerExit2D(Collider2D collision)
        {
            moveSpeed = -moveSpeed;
            FlipSprite();
        }

        void FlipSprite()
        {
            transform.localScale = new Vector2(-transform.localScale.x, transform.localScale.y);
        }
    

   
  }

